name: CI Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"
      DATABASE_URL: "sqlite:///oc-lettings-site.sqlite3"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt

      - name: Write .env file
        run: |
          echo "SECRET_KEY='${{ secrets.SECRET_KEY }}'" > .env
          echo "SENTRY_DSN='${{ secrets.SENTRY_DSN }}'" >> .env
          echo "DJANGO_ALLOWED_HOSTS='${{ secrets.DJANGO_ALLOWED_HOSTS }}'" >> .env

      - name: Run linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
          coverage xml
        continue-on-error: true

      - name: Check coverage threshold
        run: |
          coverage report --fail-under=80

      - name: Collect static files
        run: |
          source .env
          python manage.py collectstatic --noinput

      - name: Upload codebase artifact
        uses: actions/upload-artifact@v4
        with:
          path: .
          name: codebase

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download codebase artifact
        uses: actions/download-artifact@v4
        with:
          name: codebase

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mydjangoapp:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/mydjangoapp:latest

      - name: Provision docker-compose.yml
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "docker-compose.yml"
          target: "$HOME/app/"
          overwrite: true

      - name: Provision Caddyfile
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "Caddyfile"
          target: "$HOME"
          overwrite: true

      - name: Move Caddyfile to /etc/caddy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo mv $HOME/Caddyfile /etc/caddy/Caddyfile
            sudo chown root:root /etc/caddy/Caddyfile
            sudo chmod 644 /etc/caddy/Caddyfile

      - name: Write .env file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "COMMIT_SHA=${{ github.sha }}" >> $HOME/app/.env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $HOME/app/.env
            echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $HOME/app/.env
            echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> $HOME/app/.env
          

      - name: Deploy to VPS using Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd $HOME/app/
            sudo docker-compose pull
            sudo docker-compose up -d --remove-orphans

            