name: CI Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
